
#Initialization of constant long-lived page access token to page : Tigrupo7
 ACCESS_TOKEN = 'EAABotInREWUBAIDlrcHt9SrTVo5ELhMKB5i7Q1OaRrBZBah6HVNZAEaYecZCgHYSYiy2JoHem3w0YBTyP3VCG6ebsMfrZASrRr2k7rT4PId470xdzuRFfYT3dUvFcHftHfIjUtE4UZCZBLN10Iml1Uetvf7yO8huDubcT87jZAZCoQZDZD'
